### ISSUE TITLE
Error: package androidx.core.content does not exist.

### ISSUE THREAD

**Issue by fayepaje** [OutSystems/cordova-outsystems-fileviewer#9]
Encountered the following error upon app generation:
_Error compiling Cordova plugin: main/java/com/outsystems/plugins/fileviewer/OSOpenDocument.java:12: error: package androidx.core.content does not exist._

Any suggestion on how fix the error? Thank you so much in advance!

**Comment by CarlsCorrea** [comment]
Hello,

Do you have the property to enable androidX?

**Comment by fayepaje** [comment]
Hi,

Sorry, may I know where I can check that in OutSystems?

**Comment by fayepaje** [comment]
Thank you so much! I configured my app to enable use of AndroidX and it worked!
